baseURL = "https://dyzipp.com/"
languageCode = "en-us"
title = "Daniel Y. Zipp"
theme = "hugo-resume"
enableEmoji = true

[params]
  author = "Dan Zipp"
  description = "."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  address = "Rollinsford, NH"
  favicon = "/favicon.ico"
  firstName = "Eddie"
  lastName = "Webb"
  phone = "1-555-555-1234"
  profileImage = "img/TechChat.png"
  showEducation = true
  showExperience = true
  showOpenSource = false
  showProjects = true
  showPublications = true
  showQr = false
  showSkills = true

[permalinks]
  "/" = "/:filename"


[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "s3"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
 URL = "s3://dyzipp.com?region=us-east-2"
