name: Build and Deploy

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
        env:
          HUGO_VERSION: 0.80.0
      - name: Look at directory
        run: ls -l $GITHUB_WORKSPACE
      - name: Hugo Build
        run: $GITHUB_WORKSPACE/hugo --verboseLog
      - name: Deploy to S3
        run: $GITHUB_WORKSPACE/hugo deploy --verboseLog
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
